config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'root#index'

  resources :users, :items, :addresses, :favorites, :categories,
  :availabilities, :purchases, :pictures, :prices, :buildings, :conditions,
  :statuses, :carts, :offers

  get('/my_cart', { :controller => 'carts', :action => 'my_index' })

  get('/replyoffer', { :controller => 'transaction', :action => 'replyoffer', :as => "reply"  })
  get('/email_offer/:seller_id', { :controller => 'transaction', :action => 'new_email_offer', :as => "new_email_offer"  })
  get('/send_email_offer/:buyer_id/:seller_id', { :controller => 'transaction', :action => 'send_email_offer', :as => "send_email_offer"})

  get('/about', { :controller => 'root', :action => 'about', :as => "about"  })
  get('/help', { :controller => 'root', :action => 'help', :as => "help"  })
  get('/buy', { :controller => 'general', :action => 'buy', :as => "buy" })
  patch('/disable/:id', { :controller => 'general', :action => 'disable' })

  get('/sell', { :controller => 'general', :action => 'sell', :as => "sell" })
  get('/summary', { :controller => 'general', :action => 'summary', :as => "summary" })
  patch('/sell/:id', { :controller => 'general', :action => 'put_on_sale' })
  patch('/address/:id/main', { :controller => 'addresses', :action => 'make_main' })

  get('/pictures/item/:id', { :controller => 'pictures', :action => 'index_item' })
  put('/pictures/default/:id', { :controller => 'pictures', :action => 'make_default' })

  # CREATE
  #get('/users/new', { :controller => 'users', :action => 'new', :as => "new" })
  #post('/users', { :controller => 'users', :action => 'create', :as => "create"  })

  # READ
  #get('/users', { :controller => 'users', :action => 'index' })
  #get('/users/:id', { :controller => 'users', :action => 'show', :as=>"show"})

  # UPDATE
  #get('/users/:id/edit', { :controller => 'users', :action => 'edit', :as=>"edit" })
  #put('/users/:id', { :controller => 'users', :action => 'update', :as => "update" })

  # DELETE
  #delete('/users/:id', { :controller => 'users', :action => 'destroy' })

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  # TODO: user association
  # TODO: item association

  before_action :authenticate_user!
  before_action :check_if_admin

  def check_if_admin
    if not current_user.admin?
      redirect_to "/"
    end
  end

  def create
    @favorite = Favorite.new
    @favorite.user_id = params[:user_id]
    @favorite.item_id = params[:item_id]

    if @favorite.save
      redirect_to "/favorites", :notice => "favorite created successfully."
    else
      render "new_form"
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to "/favorites", :notice => "favorite deleted successfully."
  end

  def edit
    @favorite = Favorite.find(params[:id])
  end

  def index
    @favorites = Favorite.all
  end

  def new
    @favorite = Favorite.new
  end

  def show
    @favorite = Favorite.find(params[:id])
  end

  def update
    @favorite = Favorite.find(params[:id])
    @favorite.user_id = params[:user_id]
    @favorite.item_id = params[:item_id]

    if @favorite.save
      redirect_to "/favorites", :notice => "favorite updated successfully."
    else
      render "new_form"
    end
  end
end

app/views/favorites/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_tag favorite_path(@favorite), :class => "form-horizontal", :method => "put" do %>
      <!-- Label and input for user_id -->
      <div class="form-group">
        <label for="user_id" class="col-sm-3 control-label">
          Name
        </label>
        <div class="col-sm-4">
          <%= text_field_tag 'user_id', @favorite.user_id, class: 'form-control' %>
        </div>
      </div>

      <!-- Label and input for favorite_id -->
      <div class="form-group">
        <label for="item_id" class="col-sm-3 control-label">
          Name
        </label>
        <div class="col-sm-4">
          <%= text_field_tag 'item_id', @favorite.item_id, class: 'form-control' %>
        </div>
      </div>

      <!-- CREATE BUTTON -->
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-9">
          <%= submit_tag "Update favorite", :class => "btn btn-primary" %>
        </div>
      </div>

    <div class="col-md-12">
      <%= link_to "Go back", favorites_path %>
    </div>
    <% end %>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Manage favorites</h3>

    <%= link_to "Add new favorite", new_favorite_path, :class => "btn btn-primary" %>
    <p>&nbsp</p>

    <table class="table table-striped">
      <tr>
        <th>User</th>
        <th>Item</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user_id %></td>
        <td><%= favorite.item_id %></td>
        <td>
         <%= link_to "View", favorite_path(favorite.id) %>
        </td>
        <td>
          <%= link_to "Edit", edit_favorite_path(favorite.id) %>
        </td>

        <td>
          <%= link_to "Delete", favorite_path(favorite.id), :method => "delete", data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/favorites/new.html.erb
<!-- Validation failure messages -->
  <% if @favorite.errors.any? %>
    <% @favorite.errors.full_messages.each do |message| %>
      <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= message %>
      </div>
    <% end %>
  <% end %>

<div class="row">
  <div class="col-md-12">

    <%= form_tag "/favorites", :class => "form-horizontal", :method => "post" do %>

      <!-- Label and input for user_id -->
      <div class="form-group">
        <label for="user_id" class="col-sm-3 control-label">
          user_id
        </label>
        <div class="col-sm-4">
          <%= text_field_tag 'user_id', nil, class: 'form-control' %>
        </div>
      </div>

      <!-- Label and input for item_id -->
      <div class="form-group">
        <label for="item_id" class="col-sm-3 control-label">
          item_id
        </label>
        <div class="col-sm-4">
          <%= text_field_tag 'item_id', nil, class: 'form-control' %>
        </div>
      </div>

      <!-- CREATE BUTTON -->
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-9">
          <%= submit_tag "Create new favorite", :class => "btn btn-primary" %>
        </div>
      </div>

    <% end %>
    <div class="col-md-12">
      <%= link_to "Go back", favorites_path %>
    </div>
  </div>
</div>

app/views/favorites/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Favorite #<%= @favorite.id %> data</h3>
    <dl class="dl-horizontal">
      <dt>User</dt>
      <dd><%= @favorite.user_id %></dd>
      <dt>Item</dt>
      <dd><%= @favorite.item_id %></dd>
    </dl>
    <%= link_to "Go back", favorites_path %>
  </div>
</div>