config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'root#index'

  resources :users, :items, :addresses, :favorites, :categories,
  :availabilities, :purchases, :pictures, :prices, :buildings, :conditions,
  :statuses, :carts, :offers

  get('/my_cart', { :controller => 'carts', :action => 'my_index' })

  get('/replyoffer', { :controller => 'transaction', :action => 'replyoffer', :as => "reply"  })
  get('/email_offer/:seller_id', { :controller => 'transaction', :action => 'new_email_offer', :as => "new_email_offer"  })
  get('/send_email_offer/:buyer_id/:seller_id', { :controller => 'transaction', :action => 'send_email_offer', :as => "send_email_offer"})

  get('/about', { :controller => 'root', :action => 'about', :as => "about"  })
  get('/help', { :controller => 'root', :action => 'help', :as => "help"  })
  get('/buy', { :controller => 'general', :action => 'buy', :as => "buy" })
  patch('/disable/:id', { :controller => 'general', :action => 'disable' })

  get('/sell', { :controller => 'general', :action => 'sell', :as => "sell" })
  get('/summary', { :controller => 'general', :action => 'summary', :as => "summary" })
  patch('/sell/:id', { :controller => 'general', :action => 'put_on_sale' })
  patch('/address/:id/main', { :controller => 'addresses', :action => 'make_main' })

  get('/pictures/item/:id', { :controller => 'pictures', :action => 'index_item' })
  put('/pictures/default/:id', { :controller => 'pictures', :action => 'make_default' })

  # CREATE
  #get('/users/new', { :controller => 'users', :action => 'new', :as => "new" })
  #post('/users', { :controller => 'users', :action => 'create', :as => "create"  })

  # READ
  #get('/users', { :controller => 'users', :action => 'index' })
  #get('/users/:id', { :controller => 'users', :action => 'show', :as=>"show"})

  # UPDATE
  #get('/users/:id/edit', { :controller => 'users', :action => 'edit', :as=>"edit" })
  #put('/users/:id', { :controller => 'users', :action => 'update', :as => "update" })

  # DELETE
  #delete('/users/:id', { :controller => 'users', :action => 'destroy' })

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :buyer, class_name: "User", foreign_key: "id"
  belongs_to :item

  validates :buyer_id, presence: true
  validates :item_id, presence: true
  validates :item_id, uniqueness: { scope: :buyer_id,
    message: "already in cart" }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  # TODO: check the check_if_admin functions
  before_action :authenticate_user!
  before_action :check_if_admin, only: [:index]

  def check_if_admin
    if not current_user.admin?
      redirect_to "/"
    end
  end

  def create
    @cart = Cart.new
    @cart.buyer_id = params[:buyer_id]
    @cart.item_id = params[:item_id]

    if @cart.save
      redirect_to "/my_cart", :notice => "Item added to cart."
    else
      redirect_to "/my_cart"
    end
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_to "/my_cart", :notice => "Item successfully removed from cart."
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def my_index
    @carts = Cart.where(:buyer_id => current_user.id)
    #@sellers = Cart.where(:buyer_id => current_user.id).joins(item: :user).select(:name).distinct
    @sellers = Cart.where(:buyer_id => current_user.id).joins(:item).select(:user_id).distinct
    # @batman = User.where(:user_id => @sellers_id.user_id)


    @pictures = Picture.all
  end

  def index
    @carts = Cart.all
  end

  def new
    @cart = Cart.new
  end

  def show
    @cart = Cart.find(params[:id])
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.buyer_id = params[:buyer_id]
    @cart.item_id = params[:item_id]

    if @cart.save
      redirect_to "/carts", :notice => "Cart item successfully updated."
    else
      render "new_form"
    end
  end
end

app/views/carts/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_tag cart_path(@cart), :class => "form-horizontal", :method => "put" do %>
      <!-- Label and input for buyer_id -->
      <div class="form-group">
        <label for="buyer_id" class="col-sm-3 control-label">
          Buyer id
        </label>
        <div class="col-sm-4">
          <%= text_field_tag 'buyer_id', @cart.buyer_id, class: 'form-control' %>
        </div>
      </div>

      <!-- Label and input for cart_id -->
      <div class="form-group">
        <label for="item_id" class="col-sm-3 control-label">
          Name
        </label>
        <div class="col-sm-4">
          <%= text_field_tag 'item_id', @cart.item_id, class: 'form-control' %>
        </div>
      </div>

      <!-- CREATE BUTTON -->
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-9">
          <%= submit_tag "Update cart", :class => "btn btn-primary" %>
        </div>
      </div>

    <div class="col-md-12">
      <%= link_to "Go back", carts_path %>
    </div>
    <% end %>
  </div>
</div>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Manage carts</h3>

    <%= link_to "Add new item on cart", new_cart_path, :class => "btn btn-primary" %>
    <p>&nbsp</p>

    <table class="table table-striped">
      <tr>
        <th>Buyer</th>
        <th>Buyer_id</th>
        <th>Item</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @carts.each do |cart| %>
      <tr>
        <td>
          <% if !cart.buyer_id.nil? %>
            <%= User.find(cart.buyer_id).name %>
          <% end %>
        </td>
        <td>
          <%= cart.buyer_id %>
        </td>
        <td><%= cart.item.title %></td>

        <td>
         <%= link_to "View", cart_path(cart.id) %>
        </td>
        <td>
          <%= link_to "Edit", edit_cart_path(cart.id) %>
        </td>

        <td>
          <%= link_to "Delete", cart_path(cart.id), :method => "delete", data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/carts/my_index.html.erb
<div class="row">
  <div class="col-md-12">
    <% if @carts.length==0 %>
      <h3>Your shopping cart is empty</h3>
      <p>Why don't you look for   <%= link_to "something that might interest you?", "/buy" %> </p>
    <% else %>
      <h3>Yout shopping cart</h3>
      <% @sellers.each do |seller| %>
        <br>
        <h4>Items from <%= User.find(seller.user_id).name %></h4>
        <% @carts.each do |cart| %>
          <% if cart.item.user_id == seller.user_id %>
            <div class="row summary-item-frame">
              <div class="col-md-3 summary-item-picture-frame">
                <a href="/items/<%= cart.item.id %>"><img class="summary-item-picture"
                <% if !@pictures.where(:item_id => cart.item.id).first.nil? %>
                  src="<%= @pictures.where(:item_id => cart.item.id).first.image.url %>"
                <% else %>
                src="/assets/default_picture.png"
                <% end %>
                ></a>
              </div>
              <div class="col-md-9 summary-item-data">
                <a class="summary-item-name" href="/items/<%= cart.item.id %>"><%= cart.item.title %></a>
                <ul>
                  <li>On sale by <%= cart.item.user.name %></li>
                  <li>Added on cart on <%= cart.created_at.strftime("%D") %></li>
                </ul>
                <%= link_to "Remove from cart", cart_path(cart.id), :method => "delete", data: {confirm: "Are you sure?"}, :class => "btn btn-default" %>
              </div>
            </div>
            <br>
          <% end %>
        <% end %>
        <%= link_to "Make offer to "+User.find(seller.user_id).name.to_s, new_email_offer_path(seller.user_id), :method => "get", class: "btn btn-lg btn-primary" %>
        <br>
      <% end %>
    <% end %>
  </div>
</div>

app/views/carts/new.html.erb
<!-- Validation failure messages -->
  <% if @cart.errors.any? %>
    <% @cart.errors.full_messages.each do |message| %>
      <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= message %>
      </div>
    <% end %>
  <% end %>

<div class="row">
  <div class="col-md-12">

    <%= form_tag carts_path, :class => "form-horizontal", :method => "post" do %>

      <!-- Label and input for buyer_id -->
      <div class="form-group">
        <label for="buyer_id" class="col-sm-3 control-label">
          buyer_id
        </label>
        <div class="col-sm-4">
          <%= text_field_tag 'buyer_id', nil, class: 'form-control' %>
        </div>
      </div>

      <!-- Label and input for item_id -->
      <div class="form-group">
        <label for="item_id" class="col-sm-3 control-label">
          item_id
        </label>
        <div class="col-sm-4">
          <%= text_field_tag 'item_id', nil, class: 'form-control' %>
        </div>
      </div>

      <!-- CREATE BUTTON -->
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-9">
          <%= submit_tag "Add item to cart", :class => "btn btn-primary" %>
        </div>
      </div>

    <% end %>
    <div class="col-md-12">
      <%= link_to "Go back", carts_path %>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Cart #<%= @cart.id %> data</h3>
    <dl class="dl-horizontal">
      <dt>Buyer ID</dt>
      <dd><%= @cart.buyer_id %></dd>
      <dt>Item owner ID</dt>
      <dd><%= Item.find(@cart.item_id).user.name %></dd>
      <dt>Item</dt>
      <dd><%= @cart.item_id %></dd>
    </dl>
    <%= link_to "Go back", carts_path %>
  </div>
</div>