config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'root#index'

  resources :users, :items, :addresses, :favorites, :categories,
  :availabilities, :purchases, :pictures, :prices, :buildings, :conditions,
  :statuses, :carts, :offers

  get('/my_cart', { :controller => 'carts', :action => 'my_index' })

  get('/replyoffer', { :controller => 'transaction', :action => 'replyoffer', :as => "reply"  })
  get('/email_offer/:seller_id', { :controller => 'transaction', :action => 'new_email_offer', :as => "new_email_offer"  })
  get('/send_email_offer/:buyer_id/:seller_id', { :controller => 'transaction', :action => 'send_email_offer', :as => "send_email_offer"})

  get('/about', { :controller => 'root', :action => 'about', :as => "about"  })
  get('/help', { :controller => 'root', :action => 'help', :as => "help"  })
  get('/buy', { :controller => 'general', :action => 'buy', :as => "buy" })
  patch('/disable/:id', { :controller => 'general', :action => 'disable' })

  get('/sell', { :controller => 'general', :action => 'sell', :as => "sell" })
  get('/summary', { :controller => 'general', :action => 'summary', :as => "summary" })
  patch('/sell/:id', { :controller => 'general', :action => 'put_on_sale' })
  patch('/address/:id/main', { :controller => 'addresses', :action => 'make_main' })

  get('/pictures/item/:id', { :controller => 'pictures', :action => 'index_item' })
  put('/pictures/default/:id', { :controller => 'pictures', :action => 'make_default' })

  # CREATE
  #get('/users/new', { :controller => 'users', :action => 'new', :as => "new" })
  #post('/users', { :controller => 'users', :action => 'create', :as => "create"  })

  # READ
  #get('/users', { :controller => 'users', :action => 'index' })
  #get('/users/:id', { :controller => 'users', :action => 'show', :as=>"show"})

  # UPDATE
  #get('/users/:id/edit', { :controller => 'users', :action => 'edit', :as=>"edit" })
  #put('/users/:id', { :controller => 'users', :action => 'update', :as => "update" })

  # DELETE
  #delete('/users/:id', { :controller => 'users', :action => 'destroy' })

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :item

  validates :image, attachment_presence: true
  validates :item_id, presence: true

  #validates_attachment :image, :presence => true,
  #:content_type => { :content_type => "image/jpg" },
  #:size => { :in => 0..100.kilobytes }

  #Paperclip.options[:command_path] = 'C:\Program Files\ImageMagick-6.9.0-Q16'

  has_attached_file :image, styles: {
      thumbnail: "80x80",
      med: "300x300",
      large: "500x500"
  }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_action :authenticate_user!
  before_action :check_if_admin, only:[:index]

  def check_if_admin
    if not current_user.admin?
      redirect_to "/"
    end
  end


  def create
    @picture = Picture.new
    @picture.item_id = params[:item_id]
    @picture.image = params[:picture][:image]
    # Makes sure there is only 1 default_picture for every item
    @default = Picture.where(:item_id => @picture.item_id, :default_picture =>true ) #all pictures from the same item which are default
    if params[:default_picture]
      @default.each do |picture|
        picture.default_picture = false
        picture.save
      end
    end

    @picture.default_picture = params[:default_picture]

    if @picture.save
      redirect_to "/pictures/item/"+@picture.item_id.to_s, :notice => "Picture created successfully."
    else
      render "new"
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    item_id = @picture.item_id
    item = Item.find(item_id)
    if item.user_id == current_user.id
      @picture.destroy
      redirect_to "/pictures/item/"+@picture.item_id.to_s, :notice => "Picture deleted."
    else
      redirect_to "/"
    end
  end

  def edit
    @picture = Picture.find(params[:id])
    item = Item.find(@picture.item_id)
    if !item.user_id == current_user.id
      redirect_to "/"
    end
  end

  def index
    @pictures = Picture.all
  end

  def index_item
    @item = Item.find(params[:id])
    if @item.user_id == current_user.id || current_user.admin?
      @picture = Picture.new
      @pictures = Picture.where(:item_id => params[:id])
    else
      redirect_to "/"
    end
  end

  def new
    @picture = Picture.new
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def make_default
    @picture = Picture.find(params[:id])

    # Makes sure there is only 1 default_picture for every item
    @default = Picture.where(:item_id => @picture.item_id, :default_picture =>true ) #all pictures from the same item which are default
    @default.each do |picture|
      picture.default_picture = false
      picture.save
    end

    @picture.default_picture = true

    if @picture.save
      redirect_to "/pictures/item/"+@picture.item_id.to_s, :notice => "Changes succesfull"
    else
      render "index_item"
    end
  end

  def update
    @picture = Picture.find(params[:id])
    @picture.item_id = params[:item_id]

    # Makes sure there is only 1 default_picture for every item
    @default = Picture.where(:item_id => @picture.item_id, :default_picture =>true ) #all pictures from the same item which are default
    if params[:default_picture]
      @default.each do |picture|
        picture.default_picture = false
        picture.save
      end
    end

    @picture.default_picture = params[:default_picture]

    if @picture.save
      redirect_to "/pictures", :notice => "Picture updated successfully."
    else
      render "edit"
    end
  end
end

app/views/pictures/edit.html.erb
<!-- Validation failure messages -->
<% if @picture.errors.any? %>
  <% @picture.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-12">
    <%= form_for @picture, :url=> picture_path, :html => { multipart: true, :class => "form-horizontal", :method => "patch" } do |f| %>

      <!-- Label and input for item_id -->
      <div class="form-group">
        <label for="item_id" class="col-sm-3 control-label">
          Item title
        </label>
        <div class="col-sm-4">
            <%= select_tag :item_id, options_from_collection_for_select(Item.all, :id, :title, @picture.item_id), include_blank: true,  class: 'form-control' %>
        </div>
      </div>

      <!-- Label and input for image -->
      <div class="form-group">
        <label for="item_id" class="col-sm-3 control-label">
          Image location
        </label>
        <div class="col-sm-4">
          <em>Note: you cannot change your file - you will need to delete and submit a new one.</em>
        </div>
        <BR><BR>
        <div class="col-sm-4 col-sm-offset-3">
          <%= link_to image_tag(@picture.image.url(:med), align:"middle", style:"border: 1px solid black"), @picture.image.url, align:"center"  %>
        </div>
      </div>

      <!-- main_picture checkbox -->
      <div class="form-group">
        <div class="col-sm-9 col-sm-offset-3">
          <div class="checkbox">
            <label>
              <%= check_box_tag 'default_picture', true, @picture.default_picture? %>
              Default picture for the item?
            </label>
          </div>
        </div>
      </div>

      <!-- CREATE BUTTON -->
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-9">
          <%= f.submit "Update picture", :class => "btn btn-primary" %>
        </div>
      </div>

    <% end %>

    <div class="col-md-12">
      <%= link_to "Go back", pictures_path %>
      <br>
    </div>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Manage pictures</h3>

    <%= link_to "Add new picture", new_picture_path, :class => "btn btn-primary" %>
    <p>&nbsp</p>
    <table class="table table-striped">
      <tr>
        <th>Item</th>
        <th>Default?</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.item.title %></td>
        <td><%= picture.default_picture %></td>
        <td>
         <%= link_to "View", picture_path(picture.id) %>
        </td>
        <td>
          <%= link_to "Edit", edit_picture_path(picture.id) %>
        </td>

        <td>
          <%= link_to "Delete", picture_path(picture.id), :method => "delete", data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/pictures/index_item.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3><%= link_to @item.title, item_path(@item.id)  %></h3>
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Upload a new picture</h3>
        </div>
        <div class="panel-body">
    <%= form_for @picture, :url=> pictures_path, :html => { multipart: true, :class => "form-horizontal", :method => "post" } do |f| %>

      <!-- Label and input for item_id -->
      <%= hidden_field_tag 'item_id', @item.id, required: true, class: 'form-control' %>

      <!-- Label and input for image -->
      <div class="form-group">
        <label for="item_id" class="col-sm-3 control-label">
          Image location
        </label>
        <div class="col-sm-4">
          <%= f.file_field :image,  required:true %>
        </div>
      </div>

      <!-- main_picture checkbox -->
      <div class="form-group">
        <div class="col-sm-9 col-sm-offset-3">
          <div class="checkbox">
            <label>
              <%= hidden_field_tag 'default_picture', false, required: true, class: 'form-control' %>
            </label>
          </div>
        </div>
      </div>

      <!-- CREATE BUTTON -->
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-9">
          <%= f.submit "Upload picture", :class => "btn btn-primary" %>
        </div>
      </div>

    <% end %>
    </div>
      </div>


    <p>&nbsp</p>
    <table class="table">
      <% @pictures.each do |picture| %>
      <tr>
        <td style="text-align: center">
        <% if picture.default_picture? %>
            <p><em>This is your main picture (it will show in the browser, etc).</em></p>
        <% end %>
          <%= image_tag(picture.image.url(:med))  %>
        </td>
        <td>
          <% if !picture.default_picture? %>
          <%= link_to "Make this the main picture", "/pictures/default/"+ picture.id.to_s, :class=>"btn btn-default", :method => "put" %>
          <% end %>
        </td>
        <td>
          <%= link_to "Delete", picture_path(picture.id), :method => "delete", data: {confirm: "Are you sure?"}, :class=>"btn btn-default" %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <div class="col-md-12">
    <%= link_to "Go back", :back %>
    <br>
  </div>
</div>

app/views/pictures/new.html.erb
<!-- Validation failure messages -->
<% if @picture.errors.any? %>
  <% @picture.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-12">

    <%= form_for @picture, :url=> pictures_path, :html => { multipart: true, :class => "form-horizontal", :method => "post" } do |f| %>

      <!-- Label and input for item_id -->
      <div class="form-group">
        <label for="item_id" class="col-sm-3 control-label">
          Item title
        </label>
        <div class="col-sm-4">
        <%= select_tag :item_id, options_from_collection_for_select(Item.all, :id, :title), include_blank: true,  class: 'form-control' %>
        <!-- options_from_collection_for_select(Item.order("title"), :id, :title), include_blank: true,  class: 'form-control' -->
        </div>
      </div>

      <!-- Label and input for image -->
      <div class="form-group">
        <label for="item_id" class="col-sm-3 control-label">
          Image location
        </label>
        <div class="col-sm-4">
          <%= f.file_field :image %>
        </div>
      </div>

      <!-- main_picture checkbox -->
      <div class="form-group">
        <div class="col-sm-9 col-sm-offset-3">
          <div class="checkbox">
            <label>
              <%= check_box_tag 'default_picture' %>
              Default picture for the item?
            </label>
          </div>
        </div>
      </div>

      <!-- CREATE BUTTON -->
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-9">
          <%= f.submit "Upload picture", :class => "btn btn-primary" %>
        </div>
      </div>

    <% end %>

    <div class="col-md-12">
      <%= link_to "Go back", :back %>
      <br>
    </div>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Picture <%= @picture.id %> data</h3>
    <dl class="dl-horizontal">
      <dt>Item</dt>
      <dd><%= @picture.item.title %></dd>
      <dt>Default picture?</dt>
      <dd><%= @picture.default_picture %></dd>
      <br>
      <dt>Image (medium)</dt>
      <dd>
        <%= link_to image_tag(@picture.image.url(:med), align:"middle", style:"border: 1px solid black"), @picture.image.url, align:"center"  %>
      </dd>
      <br>
      <dt>Image (thumbnail)</dt>
      <dd>
        <%= link_to image_tag(@picture.image.url(:thumbnail), align:"middle", style:"border: 1px solid black"), @picture.image.url, align:"center"  %>
      </dd>

    </dl>
    <div class="col-md-12">
    </div>
    <%= link_to "Go back", :back %>
    <br>
    </div>
  </div>
</div>